name: Publish to Docker
on: 
    push:
      branches:
        - main
    release:
        types: [published]
jobs:
    publish-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
                submodules: recursive
    
          - name: Login GitHub Packages
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: lint-dockerfile
            uses: hadolint/hadolint-action@v3.1.0
            with:
                dockerfile: Dockerfile
        
          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
            with:
                images: ghcr.io/mashumabduljabbar/karsajobs-ui
    
          - name: build-karsajobs-ui
            uses: docker/build-push-action@v5
            with:
                context: .
                push: true
                labels: ${{ steps.meta.outputs.labels }}
                tags: ${{ steps.meta.outputs.tags }}, ghcr.io/mashumabduljabbar/karsajobs-ui:latest
